sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.phpunit

env:
  global:
    - SYMFONY_PHPUNIT_DIR=$HOME/.phpunit

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.0
      env: xdebug="yes" PHPUNIT_OPTIONS="--coverage-clover=coverage.clover"
    - php: 7.1
    - php: 7.2

before_install:
  - if [[ "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - vendor/bin/simple-phpunit $PHPUNIT_OPTIONS
  - if [[ "$xdebug" = "yes" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$xdebug" = "yes" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
